[tools]

gh = "latest"

bun = "latest"
deno = "latest"

node = "lts"
pnpm = "latest"
"npm:tsx" = "latest"
"npm:netserv" = "latest"
"npm:uni-run" = "latest"
"npm:code-info" = "latest"

go = "latest"
rust = "stable"

php = "latest"
java = "latest"
python = "latest"

[settings]
os = "windows"
auto_install = false
exec_auto_install = false
not_found_auto_install = false