[tools]

gh = "latest"
ni = "latest"

node = "lts"
deno = "latest"
bun = "latest"

pnpm = "latest"
yarn = "latest"
"npm:tsx" = "latest"
"npm:netserv" = "latest"
"npm:uni-run" = "latest"
"npm:code-info" = "latest"

go = "latest"
php = "latest"
rust = "stable"
ruby = "latest"
java = "latest"
dart = "latest"
python = "latest"

[settings]
os = "windows"
auto_install = false
exec_auto_install = false
not_found_auto_install = false
