[tools]

gh = "latest"

bun = "latest"
deno = "latest"

node = "lts"
pnpm = "latest"
"npm:tsx" = "latest"
"npm:netserv" = "latest"
"npm:uni-run" = "latest"
"npm:code-info" = "latest"

go = "latest"
php = "latest"
java = "latest"
rust = "latest"
python = "latest"
