[tools]

node = "latest"
deno = "latest"
bun = "latest"

ni = "latest"
pnpm = "latest"
yarn = "latest"
"npm:tsx" = "latest"
"npm:netserv" = "latest"
"npm:uni-run" = "latest"
"npm:code-info" = "latest"

go = "latest"
php = "latest"
rust = "stable"
ruby = "latest"
java = "latest"
dart = "latest"
python = "latest"
rust-analyzer = "latest"

eza = "latest"
yazi = "latest"

[settings]
os = "windows"
auto_install = false
exec_auto_install = false
not_found_auto_install = false
