[tools]

node = "lts"
ni = "latest"

bun = "latest"
deno = "latest"

"npm:tsx" = "latest"
"npm:yarn" = "latest"
"npm:pnpm" = "latest"
"npm:netserv" = "latest"
"npm:uni-run" = "latest"
"npm:code-info" = "latest"
"npm:@typescript/native-preview" = "latest"

go = "latest"
python = "latest"

php = "latest"
java = "latest"

rust = "stable"
ruby = "latest"
rust-analyzer = "latest"

dart = "latest"
kotlin = "latest"

fzf = "latest"
bat = "latest"
eza = "latest"
yazi = "latest"
tokei = "latest"

[settings]
auto_install = false
exec_auto_install = false
not_found_auto_install = false
