[tools]

bun = "latest"
deno = "latest"
node = "latest"

"npm:tsx" = "latest"
"npm:yarn" = "latest"
"npm:pnpm" = "latest"
"npm:netserv" = "latest"
"npm:uni-run" = "latest"
"npm:code-info" = "latest"
"npm:@antfu/ni" = "latest"
"npm:@openai/codex" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"

go = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"

php = "latest"
java = "latest"
python = "latest"

rust = "stable"
ruby = "latest"
rust-analyzer = "latest"

dart = "latest"
kotlin = "latest"

xh = "latest"
fd = "latest"
duf = "latest"
fzf = "latest"
bat = "latest"
eza = "latest"
lsd = "latest"
yazi = "latest"
tokei = "latest"
zoxide = "latest"
bottom = "latest"
lazygit = "latest"

[settings]
auto_install = false
exec_auto_install = false
not_found_auto_install = false
