[tools]

bun = "latest"
node = "latest"
deno = "latest"

"npm:tsx" = "latest"
"npm:yarn" = "latest"
"npm:pnpm" = "latest"
"npm:@antfu/ni" = "latest"

"npm:netserv" = "latest"
"npm:uni-run" = "latest"
"npm:code-info" = "latest"

"npm:opencode-ai" = "latest"
"npm:@openai/codex" = "latest"
"npm:@github/copilot" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"

go = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"

java = "latest"
python = "latest"

# php = "latest"
# zig = "latest"
# ruby = "latest"
# dart = "latest"
# kotlin = "latest"
# flutter = "latest"
# erlang = "stable"
# elixir = "stable"
# rust = "stable"
# rust-analyzer = "latest"

xh = "latest"
fd = "latest"
duf = "latest"
fzf = "latest"
bat = "latest"
eza = "latest"
lsd = "latest"
yazi = "latest"
tokei = "latest"
zoxide = "latest"
bottom = "latest"
lazygit = "latest"
ripgrep = "latest"

[settings]
auto_install = false
