[tools]

node = "lts"
bun = "latest"
deno = "latest"

go = "latest"
java = "latest"
python = "latest"
# php = "latest"
# zig = "latest"
# ruby = "latest"
# kotlin = "latest"
# erlang = "stable"
# elixir = "stable"

# rust = "stable"
# rust-analyzer = "latest"

"npm:tsx" = "latest"
"npm:yarn" = "latest"
"npm:pnpm" = "latest"
"npm:@antfu/ni" = "latest"

"npm:serve" = "latest"
"npm:netserv" = "latest"
"npm:uni-run" = "latest"
"npm:code-info" = "latest"
"npm:git-stats" = "latest"
"npm:npm-name-cli" = "latest"

"npm:opencode-ai" = "latest"
"npm:@openai/codex" = "latest"
"npm:@github/copilot" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"

[settings]
auto_install = false
