[tools]

# JS/TS
node = "lts"
bun = "latest"
deno = "latest"
"npm:tsx" = "latest"
"npm:yarn" = "latest"
"npm:pnpm" = "latest"
"npm:taze" = "latest"
"npm:@antfu/ni" = "latest"


# Other Languages
go = "latest"
java = "latest"
# php = "latest"
# zig = "latest"
# ruby = "latest"
# kotlin = "latest"
# rust = "stable"
# rust-analyzer = "latest"


# Python
uv = "latest"
python = "latest"


# CLI Tools
"npm:serve" = "latest"
"npm:netserv" = "latest"
"npm:uni-run" = "latest"
"npm:code-info" = "latest"
"npm:git-stats" = "latest"
"npm:npm-name-cli" = "latest"


# Hosting Tools
gcloud = "latest"
"npm:vercel" = "latest"
"npm:netlify-cli" = "latest"

[settings]
auto_install = false
