[tools]

node = "lts"
bun = "latest"
deno = "latest"

go = "latest"
java = "latest"
python = "latest"
# php = "latest"
# zig = "latest"
# ruby = "latest"
# kotlin = "latest"

# rust = "stable"
# rust-analyzer = "latest"

"npm:tsx" = "latest"
"npm:yarn" = "latest"
"npm:pnpm" = "latest"
"npm:@antfu/ni" = "latest"

"npm:serve" = "latest"
"npm:netserv" = "latest"
"npm:uni-run" = "latest"
"npm:code-info" = "latest"
"npm:git-stats" = "latest"
"npm:npm-name-cli" = "latest"

"npm:vercel" = "latest"
"npm:netlify-cli" = "latest"
"npm:firebase-tools" = "latest"

codex = "latest"
gemini = "latest"
claude = "latest"
opencode = "latest"
