[tools]

node = "lts"
ni = "latest"

bun = "latest"
deno = "latest"

"npm:tsx" = "latest"
"npm:yarn" = "latest"
"npm:pnpm" = "latest"
"npm:netserv" = "latest"
"npm:uni-run" = "latest"
"npm:code-info" = "latest"

go = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"
"go:mvdan.cc/sh/v3/cmd/shfmt" = "latest"

php = "latest"
java = "latest"
python = "latest"

rust = "stable"
ruby = "latest"
rust-analyzer = "latest"

dart = "latest"
kotlin = "latest"

fd = "latest"
duf = "latest"
fzf = "latest"
bat = "latest"
eza = "latest"
lsd = "latest"
yazi = "latest"
tokei = "latest"
zoxide = "latest"
bottom = "latest"
lazygit = "latest"

[settings]
auto_install = false
exec_auto_install = false
not_found_auto_install = false
