## Development Tools
- lua
- luajit
- shfmt
- gcc

- dart
- extras/flutter

- gh
- extras/lazygit
- extras/gitbutler

- aws
- cloudflared
- lazydocker

## AI Tools
- extras/opencode-desktop

## Visualization Tools
- extras/hwinfo
- hyperfine
- fastfetch
- bottom
- btop
- ntop
- ctop

## Shells
- mise
- gsudo
- direnv
- zoxide
- starship

## System Tools
- nircmd

## File System Tools
- ripgrep
- byenow
- fd
- duf
- rip
- dust
- fzf
- bat
- lsd
- yazi

## Workflow Tools
- make
- just

## Code Analysis and Documentation Tools
- scc
- tokei
- tldr

## Media Tools
- extras/anyburn
- extras/winrar
- extras/sharex
- imagemagick
- ffmpeg
- yt-dlp

## Fonts
- nerd-fonts/FiraCode-NF

## Communication Tools
- extras/slack
