format = "$hostname$sudo$username$directory$git_branch$git_state$git_status$line_break$shlvl$shell"
follow_symlinks = false
add_newline = false


[sudo]
disabled = false
allow_windows = true
symbol = 'ğŸ‘©â€ğŸ’» '


[directory]
style = "blue"


[git_branch]
format = "[$symbol ](dimmed)[$branch](yellow)"
symbol = "ï˜"


[git_status]
format = '[$all_status$ahead_behind](red)'
modified = "*"


[shlvl]
disabled = false
format = '[\[$shlvl\]](dimmed red) '
threshold = 2


[shell]
disabled = false
format = "[$indicator ](dimmed) "
bash_indicator = 'î¯Š'
fish_indicator = 'î¹'
zsh_indicator = 'ï’µ'
cmd_indicator = 'î¯„'
pwsh_indicator = 'î¯‡'
