add_newline = false
follow_symlinks = false

format = "$hostname$sudo$username$directory$git_branch$git_state$git_status$line_break$shlvl$shell"

[sudo]
disabled = false
allow_windows = true
symbol = 'ğŸ‘©â€ğŸ’» '

[directory]
style = "blue"

[git_branch]
format = "[ï˜](dimmed) [$branch](yellow)"

[git_status]
format = '[$all_status$ahead_behind](red)'
modified = "*"

[shlvl]
disabled = false
format = '[\[$shlvl\]](dimmed red) '
threshold = 2

[shell]
disabled = false
format = "[$indicator ](dimmed white) "
powershell_indicator = 'î¯‡'
pwsh_indicator = 'î¯‡'
cmd_indicator = 'î¯„'
fish_indicator = 'î¹'
bash_indicator = 'î¯Š'
zsh_indicator = 'ï’µ'
