add_newline = false
follow_symlinks = false

format = "$username$hostname$directory$git_branch$git_state$git_status$line_break$shell"

[shell]
disabled = false
format = "[$indicator  ](dimmed white)"
fish_indicator = ''
bash_indicator = ''

[directory]
style = "blue"

[git_branch]
format = "[](dimmed) [$branch](yellow)"

[git_status]
format = '([$all_status$ahead_behind]($style))'
modified = "*"
style = "red"
