add_newline = false
follow_symlinks = false

format = "$username$hostname$directory$git_branch$git_state$git_status$line_break$shlvl$shell"

[directory]
style = "blue"

[git_branch]
format = "[](dimmed) [$branch](yellow)"

[git_status]
format = '[$all_status$ahead_behind](red)'
modified = "*"

[shlvl]
disabled = false
format = '[\[$shlvl\] ](dimmed red)'
threshold = 2

[shell]
disabled = false
format = "[$indicator  ](dimmed white)"
powershell_indicator = ''
pwsh_indicator = ''
cmd_indicator = ''
fish_indicator = ''
bash_indicator = ''
zsh_indicator = ''
